coverage:
  status:
    project:
      default:
        target: auto  # auto compares coverage to the previous base commit
        informational: true
    patch:
      default:
        target: 100%
        informational: true

github_checks:
  annotations: true
# When modifying this file, please validate using
# curl -X POST --data-binary @codecov.yml https://codecov.io/validate
